expression =
    equality .

equality =
    comparison [ ( "=" | "<>" ) comparison ] .
    
comparison =
    term [ ( "<" | "<=" | ">" | ">=" ) term ] .

term = 
    factor { ( "+" | "-" | "or" ) factor } .

factor = 
    unary { ( "*" | "/" | "and" | "mod" ) unary } .

unary = 
    ( "-" | "+" ) unary | primary .

primary = 
   IDENTIFIER | INTEGER | REAL | BOOLEAN | CHAR | STRING
   | "(" expression ")" | "not" unary | IDENTIFIER arglist .

arglist =  "(" [ expression { "," expression } ] ")"
    